buildscript {
    repositories {
        mavenCentral()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:9.1.0'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:2.4.20'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
        maven { url "https://maven.fanmiu.com/nexus/repository/maven-public/" }
        maven { url "https://maven.pkg.github.com/compose-miuix-ui/miuix" }
        mavenLocal()
    }

    configurations.all {
        exclude group: 'com.google.guava', module: 'listenablefuture'
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}